<script type="text/javascript">

document.getElementById('M1_B'+Sno).value=document.getElementById("Tot21P").value; document.getElementById('M2_B'+Sno).value=document.getElementById("Tot22P").value; document.getElementById('M3_B'+Sno).value=document.getElementById("Tot23P").value; document.getElementById('M4_B'+Sno).value=document.getElementById("Tot24P").value; document.getElementById('M5_B'+Sno).value=document.getElementById("Tot25P").value;	document.getElementById('M6_B'+Sno).value=document.getElementById("Tot26P").value; document.getElementById('M7_B'+Sno).value=document.getElementById("Tot27P").value; document.getElementById('M8_B'+Sno).value=document.getElementById("Tot28P").value;	document.getElementById('M9_B'+Sno).value=document.getElementById("Tot29P").value; document.getElementById('M10_B'+Sno).value=document.getElementById("Tot210P").value;	document.getElementById('M11_B'+Sno).value=document.getElementById("Tot211P").value; document.getElementById('M12_B'+Sno).value=document.getElementById("Tot212P").value;
	
	document.getElementById('M1_C'+Sno).value=document.getElementById("Tot31P").value; document.getElementById('M2_C'+Sno).value=document.getElementById("Tot32P").value; document.getElementById('M3_C'+Sno).value=document.getElementById("Tot33P").value; document.getElementById('M4_C'+Sno).value=document.getElementById("Tot34P").value; document.getElementById('M5_C'+Sno).value=document.getElementById("Tot35P").value;	document.getElementById('M6_C'+Sno).value=document.getElementById("Tot36P").value; document.getElementById('M7_C'+Sno).value=document.getElementById("Tot37P").value; document.getElementById('M8_C'+Sno).value=document.getElementById("Tot38P").value;	document.getElementById('M9_C'+Sno).value=document.getElementById("Tot39P").value; document.getElementById('M10_C'+Sno).value=document.getElementById("Tot310P").value;	document.getElementById('M11_C'+Sno).value=document.getElementById("Tot311P").value; document.getElementById('M12_C'+Sno).value=document.getElementById("Tot312P").value;
	  
	 document.getElementById('TotP1_TB').value=document.getElementById("Tot21T").value; document.getElementById('TotP2_TB').value=document.getElementById("Tot22T").value; document.getElementById('TotP3_TB').value=document.getElementById("Tot23T").value; document.getElementById('TotP4_TB').value=document.getElementById("Tot24T").value; document.getElementById('TotP5_TB').value=document.getElementById("Tot25T").value; document.getElementById('TotP6_TB').value=document.getElementById("Tot26T").value; document.getElementById('TotP7_TB').value=document.getElementById("Tot27T").value; document.getElementById('TotP8_TB').value=document.getElementById("Tot28T").value; document.getElementById('TotP9_TB').value=document.getElementById("Tot29T").value; document.getElementById('TotP10_TB').value=document.getElementById("Tot210T").value; document.getElementById('TotP11_TB').value=document.getElementById("Tot211T").value; document.getElementById('TotP12_TB').value=document.getElementById("Tot212T").value; 
	 	 
	 document.getElementById('TotP1_TC').value=document.getElementById("Tot31T").value; document.getElementById('TotP2_TC').value=document.getElementById("Tot32T").value; document.getElementById('TotP3_TC').value=document.getElementById("Tot33T").value; document.getElementById('TotP4_TC').value=document.getElementById("Tot34T").value; document.getElementById('TotP5_TC').value=document.getElementById("Tot35T").value; document.getElementById('TotP6_TC').value=document.getElementById("Tot36T").value; document.getElementById('TotP7_TC').value=document.getElementById("Tot37T").value; document.getElementById('TotP8_TC').value=document.getElementById("Tot38T").value; document.getElementById('TotP9_TC').value=document.getElementById("Tot39T").value; document.getElementById('TotP10_TC').value=document.getElementById("Tot310T").value; document.getElementById('TotP11_TC').value=document.getElementById("Tot311T").value; document.getElementById('TotP12_TC').value=document.getElementById("Tot312T").value;
	
	 document.getElementById('TotP2_'+Sno).value=document.getElementById("PTot2P").value; document.getElementById('TotP3_'+Sno).value=document.getElementById("PTot3P").value; document.getElementById('TotM_BeT').value=document.getElementById("TTot2T").value; document.getElementById('TotM_CeT').value=document.getElementById("TTot3T").value;
	 
</script>