<?php 
require_once('config/config.php');
if($_REQUEST['y']!=0){ $sY=mysql_query("select * from hrm_year where YearId=".$_REQUEST['y']."", $con); $rY=mysql_fetch_assoc($sY);  
$FD=date("Y",strtotime($rY['FromDate'])); $TD=date("Y",strtotime($rY['ToDate'])); $PRD=$FD.'-'.$TD; } else {$PRD='ALL'; }
/*************************************************************************************************************/

if($_REQUEST['action']='RsHCountExport') 
{ 
$csv_output .= '"",';
$csv_output .= '"",'; 
$csv_output .= '"",';
$csv_output .= '"",';
$csv_output .= '"Apr",';
$csv_output .= '"",';
$csv_output .= '"",';
$csv_output .= '"May",';
$csv_output .= '"",';
$csv_output .= '"",';
$csv_output .= '"Jun",';
$csv_output .= '"",';
$csv_output .= '"",';
$csv_output .= '"Jul",';
$csv_output .= '"",';
$csv_output .= '"",';
$csv_output .= '"Aug",';
$csv_output .= '"",';
$csv_output .= '"",';
$csv_output .= '"Sep",';
$csv_output .= '"",';
$csv_output .= '"",';
$csv_output .= '"Oct",';
$csv_output .= '"",';
$csv_output .= '"",';
$csv_output .= '"Nov",';
$csv_output .= '"",';
$csv_output .= '"",';
$csv_output .= '"Dec",';
$csv_output .= '"",';
$csv_output .= '"",';
$csv_output .= '"Jan",';
$csv_output .= '"",';
$csv_output .= '"",';
$csv_output .= '"Feb",';
$csv_output .= '"",';
$csv_output .= '"",';
$csv_output .= '"Mar",';
$csv_output .= '"",';
$csv_output .= "\n";

$csv_output .= '"SN",';
$csv_output .= '"Department",'; 
$csv_output .= '"Total",';
for($i=1; $i<=12; $i++){
$csv_output .= '"Appt",';
$csv_output .= '"Regt",';
$csv_output .= '"Emp",';
}
$csv_output .= '"Total Appt",';
$csv_output .= '"Total Regt",';
$csv_output .= '"Total Emp",';
$csv_output .= "\n";		

$today=date("Y-m-d"); $timestamp = strtotime($today); 
 $sql=mysql_query("select DepartmentId,DepartmentName from hrm_department where DeptStatus='A' AND CompanyId=".$_REQUEST['c']." order by DepartmentName ASC",$con); 
 $SNo=1; while($res=mysql_fetch_array($sql)){
 
$csv_output .= '"'.str_replace('"', '""', $Sno).'",'; 
$csv_output .= '"'.str_replace('"', '""', $res['DepartmentName']).'",';
$sqlDc=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where (hrm_employee.EmpStatus='A' OR hrm_employee.EmpStatus='D') AND hrm_employee.CompanyId=".$_REQUEST['c']." AND DateJoining<='".$FD."-03-31' AND hrm_employee_general.DepartmentId=".$res['DepartmentId'],$con); $rowDc=mysql_num_rows($sqlDc);
$csv_output .= '"'.str_replace('"', '""', $rowDc).'",';
$sql1=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where DateJoining>='".$FD."-04-01' AND DateJoining<='".$FD."-04-31' AND DepartmentId=".$res['DepartmentId']." AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); $row1=mysql_num_rows($sql1);
$sql2=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateOfResignation>='".$FD."-04-01' AND DateOfResignation<='".$FD."-04-31' AND DepartmentId=".$res['DepartmentId']." AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); 
$row2=mysql_num_rows($sql2); $Tot4=$rowDc+$row1; $TotE4=$Tot4-$row2;
$csv_output .= '"'.str_replace('"', '""', $row1).'",';
$csv_output .= '"'.str_replace('"', '""', $row2).'",';
$csv_output .= '"'.str_replace('"', '""', $TotE4).'",';
$sql1=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateJoining>='".$FD."-05-01' AND DateJoining<='".$FD."-05-31' AND DepartmentId=".$res['DepartmentId']." AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); $row1=mysql_num_rows($sql1);
$sql2=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateOfResignation>='".$FD."-05-01' AND DateOfResignation<='".$FD."-05-31' AND DepartmentId=".$res['DepartmentId']." AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); 
$row2=mysql_num_rows($sql2); $Tot5=$TotE4+$row1; $TotE5=$Tot5-$row2;
$csv_output .= '"'.str_replace('"', '""', $row1).'",';
$csv_output .= '"'.str_replace('"', '""', $row2).'",';
$csv_output .= '"'.str_replace('"', '""', $TotE5).'",';
$sql1=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateJoining>='".$FD."-06-01' AND DateJoining<='".$FD."-06-31' AND DepartmentId=".$res['DepartmentId']." AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); $row1=mysql_num_rows($sql1);
$sql2=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateOfResignation>='".$FD."-06-01' AND DateOfResignation<='".$FD."-06-31' AND DepartmentId=".$res['DepartmentId']." AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); 
$row2=mysql_num_rows($sql2); $Tot6=$TotE5+$row1; $TotE6=$Tot6-$row2;
$csv_output .= '"'.str_replace('"', '""', $row1).'",';
$csv_output .= '"'.str_replace('"', '""', $row2).'",';
$csv_output .= '"'.str_replace('"', '""', $TotE6).'",';
$sql1=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateJoining>='".$FD."-07-01' AND DateJoining<='".$FD."-07-31' AND DepartmentId=".$res['DepartmentId']." AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); $row1=mysql_num_rows($sql1);
$sql2=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateOfResignation>='".$FD."-07-01' AND DateOfResignation<='".$FD."-07-31' AND DepartmentId=".$res['DepartmentId']." AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); 
$row2=mysql_num_rows($sql2); $Tot7=$TotE6+$row1; $TotE7=$Tot7-$row2;
$csv_output .= '"'.str_replace('"', '""', $row1).'",';
$csv_output .= '"'.str_replace('"', '""', $row2).'",';
$csv_output .= '"'.str_replace('"', '""', $TotE7).'",';
$sql1=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateJoining>='".$FD."-08-01' AND DateJoining<='".$FD."-08-31' AND DepartmentId=".$res['DepartmentId']." AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); $row1=mysql_num_rows($sql1);
$sql2=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateOfResignation>='".$FD."-08-01' AND DateOfResignation<='".$FD."-08-31' AND DepartmentId=".$res['DepartmentId']." AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); 
$row2=mysql_num_rows($sql2); $Tot8=$TotE7+$row1; $TotE8=$Tot8-$row2;
$csv_output .= '"'.str_replace('"', '""', $row1).'",';
$csv_output .= '"'.str_replace('"', '""', $row2).'",';
$csv_output .= '"'.str_replace('"', '""', $TotE8).'",';
$sql1=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateJoining>='".$FD."-09-01' AND DateJoining<='".$FD."-09-31' AND DepartmentId=".$res['DepartmentId']." AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); $row1=mysql_num_rows($sql1);
$sql2=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateOfResignation>='".$FD."-09-01' AND DateOfResignation<='".$FD."-09-31' AND DepartmentId=".$res['DepartmentId']." AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); 
$row2=mysql_num_rows($sql2); $Tot9=$TotE8+$row1; $TotE9=$Tot9-$row2;
$csv_output .= '"'.str_replace('"', '""', $row1).'",';
$csv_output .= '"'.str_replace('"', '""', $row2).'",';
$csv_output .= '"'.str_replace('"', '""', $TotE9).'",';
$sql1=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateJoining>='".$FD."-10-01' AND DateJoining<='".$FD."-10-31' AND DepartmentId=".$res['DepartmentId']." AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); $row1=mysql_num_rows($sql1);
$sql2=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateOfResignation>='".$FD."-10-01' AND DateOfResignation<='".$FD."-10-31' AND DepartmentId=".$res['DepartmentId']." AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); 
$row2=mysql_num_rows($sql2); $Tot10=$TotE9+$row1; $TotE10=$Tot10-$row2;
$csv_output .= '"'.str_replace('"', '""', $row1).'",';
$csv_output .= '"'.str_replace('"', '""', $row2).'",';
$csv_output .= '"'.str_replace('"', '""', $TotE10).'",';
$sql1=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateJoining>='".$FD."-11-01' AND DateJoining<='".$FD."-11-31' AND DepartmentId=".$res['DepartmentId']." AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); $row1=mysql_num_rows($sql1);
$sql2=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateOfResignation>='".$FD."-11-01' AND DateOfResignation<='".$FD."-11-31' AND DepartmentId=".$res['DepartmentId']." AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); 
$row2=mysql_num_rows($sql2); $Tot11=$TotE10+$row1; $TotE11=$Tot11-$row2;
$csv_output .= '"'.str_replace('"', '""', $row1).'",';
$csv_output .= '"'.str_replace('"', '""', $row2).'",';
$csv_output .= '"'.str_replace('"', '""', $TotE11).'",';
$sql1=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateJoining>='".$FD."-12-01' AND DateJoining<='".$FD."-12-31' AND DepartmentId=".$res['DepartmentId']." AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); $row1=mysql_num_rows($sql1);
$sql2=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateOfResignation>='".$FD."-12-01' AND DateOfResignation<='".$FD."-12-31' AND DepartmentId=".$res['DepartmentId']." AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); 
$row2=mysql_num_rows($sql2); $Tot12=$TotE11+$row1; $TotE12=$Tot12-$row2;
$csv_output .= '"'.str_replace('"', '""', $row1).'",';
$csv_output .= '"'.str_replace('"', '""', $row2).'",';
$csv_output .= '"'.str_replace('"', '""', $TotE12).'",';
$sql1=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateJoining>='".$TD."-01-01' AND DateJoining<='".$TD."-01-31' AND DepartmentId=".$res['DepartmentId']." AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); $row1=mysql_num_rows($sql1);
$sql2=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateOfResignation>='".$TD."-01-01' AND DateOfResignation<='".$TD."-01-31' AND DepartmentId=".$res['DepartmentId']." AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); 
$row2=mysql_num_rows($sql2); $Tot1=$TotE12+$row1; $TotE1=$Tot1-$row2;
$csv_output .= '"'.str_replace('"', '""', $row1).'",';
$csv_output .= '"'.str_replace('"', '""', $row2).'",';
$csv_output .= '"'.str_replace('"', '""', $TotE1).'",';
$sql1=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateJoining>='".$TD."-02-01' AND DateJoining<='".$TD."-02-31' AND DepartmentId=".$res['DepartmentId']." AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); $row1=mysql_num_rows($sql1);
$sql2=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateOfResignation>='".$TD."-02-01' AND DateOfResignation<='".$TD."-02-31' AND DepartmentId=".$res['DepartmentId']." AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); 
$row2=mysql_num_rows($sql2); $Tot2=$TotE1+$row1; $TotE2=$Tot2-$row2;
$csv_output .= '"'.str_replace('"', '""', $row1).'",';
$csv_output .= '"'.str_replace('"', '""', $row2).'",';
$csv_output .= '"'.str_replace('"', '""', $TotE2).'",';
$sql1=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateJoining>='".$TD."-03-01' AND DateJoining<='".$TD."-03-31' AND DepartmentId=".$res['DepartmentId']." AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); $row1=mysql_num_rows($sql1);
$sql2=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateOfResignation>='".$TD."-03-01' AND DateOfResignation<='".$TD."-03-31' AND DepartmentId=".$res['DepartmentId']." AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); 
$row2=mysql_num_rows($sql2); $Tot3=$TotE2+$row1; $TotE3=$Tot3-$row2;
$csv_output .= '"'.str_replace('"', '""', $row1).'",';
$csv_output .= '"'.str_replace('"', '""', $row2).'",';
$csv_output .= '"'.str_replace('"', '""', $TotE3).'",';
$sql1t=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateJoining>='".$FD."-04-01' AND DateJoining<='".$TD."-03-31' AND DepartmentId=".$res['DepartmentId']." AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); 
$row1t=mysql_num_rows($sql1t);
$sql2t=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateOfResignation>='".$FD."-04-01' AND DateOfResignation<='".$TD."-03-31' AND DepartmentId=".$res['DepartmentId']." AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); 
$row2t=mysql_num_rows($sql2t); $Tott=$rowDc+$row1t; $TotEt=$Tott-$row2t;
$csv_output .= '"'.str_replace('"', '""', $row1t).'",';
$csv_output .= '"'.str_replace('"', '""', $row2t).'",';
$csv_output .= '"'.str_replace('"', '""', $TotEt).'",';
$csv_output .= "\n";
$Sno++; }

$csv_output .= '"'.str_replace('"', '""', '').'",'; 
$csv_output .= '"'.str_replace('"', '""', 'TOTAL').'",';
$sqlDc=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where (hrm_employee.EmpStatus='A' OR hrm_employee.EmpStatus='D') AND hrm_employee.CompanyId=".$_REQUEST['c']." AND DateJoining<='".$FD."-03-31'",$con); $rowDc=mysql_num_rows($sqlDc);
$csv_output .= '"'.str_replace('"', '""', $rowDc).'",';
$sql1=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where DateJoining>='".$FD."-04-01' AND DateJoining<='".$FD."-04-31' AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); $row1=mysql_num_rows($sql1);
$sql2=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateOfResignation>='".$FD."-04-01' AND DateOfResignation<='".$FD."-04-31' AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); 
$row2=mysql_num_rows($sql2); $Tot4=$rowDc+$row1; $TotE4=$Tot4-$row2;
$csv_output .= '"'.str_replace('"', '""', $row1).'",';
$csv_output .= '"'.str_replace('"', '""', $row2).'",';
$csv_output .= '"'.str_replace('"', '""', $TotE4).'",';
$sql1=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateJoining>='".$FD."-05-01' AND DateJoining<='".$FD."-05-31' AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); $row1=mysql_num_rows($sql1);
$sql2=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateOfResignation>='".$FD."-05-01' AND DateOfResignation<='".$FD."-05-31' AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); 
$row2=mysql_num_rows($sql2); $Tot5=$TotE4+$row1; $TotE5=$Tot5-$row2;
$csv_output .= '"'.str_replace('"', '""', $row1).'",';
$csv_output .= '"'.str_replace('"', '""', $row2).'",';
$csv_output .= '"'.str_replace('"', '""', $TotE5).'",';
$sql1=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateJoining>='".$FD."-06-01' AND DateJoining<='".$FD."-06-31' AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); $row1=mysql_num_rows($sql1);
$sql2=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateOfResignation>='".$FD."-06-01' AND DateOfResignation<='".$FD."-06-31' AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); 
$row2=mysql_num_rows($sql2); $Tot6=$TotE5+$row1; $TotE6=$Tot6-$row2;
$csv_output .= '"'.str_replace('"', '""', $row1).'",';
$csv_output .= '"'.str_replace('"', '""', $row2).'",';
$csv_output .= '"'.str_replace('"', '""', $TotE6).'",';
$sql1=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateJoining>='".$FD."-07-01' AND DateJoining<='".$FD."-07-31' AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); $row1=mysql_num_rows($sql1);
$sql2=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateOfResignation>='".$FD."-07-01' AND DateOfResignation<='".$FD."-07-31' AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); 
$row2=mysql_num_rows($sql2); $Tot7=$TotE6+$row1; $TotE7=$Tot7-$row2;
$csv_output .= '"'.str_replace('"', '""', $row1).'",';
$csv_output .= '"'.str_replace('"', '""', $row2).'",';
$csv_output .= '"'.str_replace('"', '""', $TotE7).'",';
$sql1=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateJoining>='".$FD."-08-01' AND DateJoining<='".$FD."-08-31' AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); $row1=mysql_num_rows($sql1);
$sql2=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateOfResignation>='".$FD."-08-01' AND DateOfResignation<='".$FD."-08-31' AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); 
$row2=mysql_num_rows($sql2); $Tot8=$TotE7+$row1; $TotE8=$Tot8-$row2;
$csv_output .= '"'.str_replace('"', '""', $row1).'",';
$csv_output .= '"'.str_replace('"', '""', $row2).'",';
$csv_output .= '"'.str_replace('"', '""', $TotE8).'",';
$sql1=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateJoining>='".$FD."-09-01' AND DateJoining<='".$FD."-09-31' AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); $row1=mysql_num_rows($sql1);
$sql2=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateOfResignation>='".$FD."-09-01' AND DateOfResignation<='".$FD."-09-31' AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); 
$row2=mysql_num_rows($sql2); $Tot9=$TotE8+$row1; $TotE9=$Tot9-$row2;
$csv_output .= '"'.str_replace('"', '""', $row1).'",';
$csv_output .= '"'.str_replace('"', '""', $row2).'",';
$csv_output .= '"'.str_replace('"', '""', $TotE9).'",';
$sql1=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateJoining>='".$FD."-10-01' AND DateJoining<='".$FD."-10-31' AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); $row1=mysql_num_rows($sql1);
$sql2=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateOfResignation>='".$FD."-10-01' AND DateOfResignation<='".$FD."-10-31' AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); 
$row2=mysql_num_rows($sql2); $Tot10=$TotE9+$row1; $TotE10=$Tot10-$row2;
$csv_output .= '"'.str_replace('"', '""', $row1).'",';
$csv_output .= '"'.str_replace('"', '""', $row2).'",';
$csv_output .= '"'.str_replace('"', '""', $TotE10).'",';
$sql1=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateJoining>='".$FD."-11-01' AND DateJoining<='".$FD."-11-31' AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); $row1=mysql_num_rows($sql1);
$sql2=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateOfResignation>='".$FD."-11-01' AND DateOfResignation<='".$FD."-11-31' AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); 
$row2=mysql_num_rows($sql2); $Tot11=$TotE10+$row1; $TotE11=$Tot11-$row2;
$csv_output .= '"'.str_replace('"', '""', $row1).'",';
$csv_output .= '"'.str_replace('"', '""', $row2).'",';
$csv_output .= '"'.str_replace('"', '""', $TotE11).'",';
$sql1=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateJoining>='".$FD."-12-01' AND DateJoining<='".$FD."-12-31' AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); $row1=mysql_num_rows($sql1);
$sql2=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateOfResignation>='".$FD."-12-01' AND DateOfResignation<='".$FD."-12-31' AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); 
$row2=mysql_num_rows($sql2); $Tot12=$TotE11+$row1; $TotE12=$Tot12-$row2;
$csv_output .= '"'.str_replace('"', '""', $row1).'",';
$csv_output .= '"'.str_replace('"', '""', $row2).'",';
$csv_output .= '"'.str_replace('"', '""', $TotE12).'",';
$sql1=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateJoining>='".$TD."-01-01' AND DateJoining<='".$TD."-01-31' AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); $row1=mysql_num_rows($sql1);
$sql2=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateOfResignation>='".$TD."-01-01' AND DateOfResignation<='".$TD."-01-31' AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); 
$row2=mysql_num_rows($sql2); $Tot1=$TotE12+$row1; $TotE1=$Tot1-$row2;
$csv_output .= '"'.str_replace('"', '""', $row1).'",';
$csv_output .= '"'.str_replace('"', '""', $row2).'",';
$csv_output .= '"'.str_replace('"', '""', $TotE1).'",';
$sql1=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateJoining>='".$TD."-02-01' AND DateJoining<='".$TD."-02-31' AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); $row1=mysql_num_rows($sql1);
$sql2=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateOfResignation>='".$TD."-02-01' AND DateOfResignation<='".$TD."-02-31' AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); 
$row2=mysql_num_rows($sql2); $Tot2=$TotE1+$row1; $TotE2=$Tot2-$row2;
$csv_output .= '"'.str_replace('"', '""', $row1).'",';
$csv_output .= '"'.str_replace('"', '""', $row2).'",';
$csv_output .= '"'.str_replace('"', '""', $TotE2).'",';
$sql1=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateJoining>='".$TD."-03-01' AND DateJoining<='".$TD."-03-31' AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); $row1=mysql_num_rows($sql1);
$sql2=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateOfResignation>='".$TD."-03-01' AND DateOfResignation<='".$TD."-03-31' AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); 
$row2=mysql_num_rows($sql2); $Tot3=$TotE2+$row1; $TotE3=$Tot3-$row2;
$csv_output .= '"'.str_replace('"', '""', $row1).'",';
$csv_output .= '"'.str_replace('"', '""', $row2).'",';
$csv_output .= '"'.str_replace('"', '""', $TotE3).'",';
$sql1t=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateJoining>='".$FD."-04-01' AND DateJoining<='".$TD."-03-31' AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); 
$row1t=mysql_num_rows($sql1t);
$sql2t=mysql_query("select GeneralId from hrm_employee_general INNER JOIN hrm_employee ON hrm_employee_general.EmployeeID=hrm_employee.EmployeeID where EmpStatus!='De' AND DateOfResignation>='".$FD."-04-01' AND DateOfResignation<='".$TD."-03-31' AND hrm_employee.CompanyId=".$_REQUEST['c'], $con); 
$row2t=mysql_num_rows($sql2t); $Tott=$rowDc+$row1t; $TotEt=$Tott-$row2t;
$csv_output .= '"'.str_replace('"', '""', $row1t).'",';
$csv_output .= '"'.str_replace('"', '""', $row2t).'",';
$csv_output .= '"'.str_replace('"', '""', $TotEt).'",';
$csv_output .= "\n";

# Close the MySql connection
mysql_close($con);
# Set the headers so the file downloads
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
header("Content-Length: " . strlen($csv_output));
header("Content-type: text/x-csv");
header("Content-Disposition: attachment; filename=HeadCount_&_Attrition_".$PRD.".csv");
echo $csv_output;
exit; 
}
?>