<?php  require_once('config/config.php');
if(isset($_POST['id']) && $_POST['id']!="")
{ $id = $_POST['id']; $month = $_POST['Month']; $ComanyID = $_POST['CompanyID']; $YearID = $_POST['YearID'];
  if(date("m")==01){ if($month==12){$Y=date("Y")-1;}else{$Y=date("Y");} }
  if(date("m")!=01){ $Y=date("Y");}
  $SqlDept=mysql_query("select DepartmentName from hrm_department where DepartmentId=".$id." order by DepartmentName ASC", $con); $ResDept=mysql_fetch_array($SqlDept); ?>
<input type="hidden" name="DeptName" id="DeptName" value="<?php echo $ResDept['DepartmentName']; ?>" />
<input type="hidden" name="MonthId" id="MonthId" value="<?php echo $month; ?>" />
<input type="hidden" name="DeptId" id="DepId" value="<?php echo $id; ?>" />

<?php  ////////////////////////////////////////////////////////////_TABLE_1_//////////////////////////////////////////////////////////////////////// ?> 

<table  border="1" bgcolor="#FFFFFF" cellpadding="0" cellspacing="0" width="2400" id="table_1" style="display:inline-table;"> 
<?php $SqlEmp=mysql_query("select hrm_employee.*,hrm_employee_general.* from hrm_employee INNER JOIN hrm_employee_general ON hrm_employee.EmployeeID=hrm_employee_general.EmployeeID where hrm_employee.EmpStatus='A' AND hrm_employee_general.DepartmentId=".$id." AND hrm_employee.CompanyId=".$ComanyID." order by EmpCode ASC", $con); $Sno=1; 
$SqlRows=mysql_num_rows($SqlEmp); echo '<input type="hidden" name="EmpRows" id="EmpRows" value='.$SqlRows.' />'; while($ResEmp=mysql_fetch_array($SqlEmp)) { ?>
<tr>
<td style="color:#000;font-family:Times New Roman; width:40px; font-size:14px; height:20px;" align="left">&nbsp;<?php echo $Sno; ?></td>
<td style="color:#000;font-family:Times New Roman; width:80px; font-size:14px;height:20px;" align="left">&nbsp;<?php echo $ResEmp['EmpCode']; ?></td>
<td style="color:#000;font-family:Times New Roman; width:180px; font-size:14px;height:20px;" align="left">&nbsp;<?php echo $ResEmp['Fname'].' '.$ResEmp['Sname'].' '.$ResEmp['Lname']; ?>
<input type="hidden" name="EmpId" id="EmpId" value="<?php echo $ResEmp['EmployeeID']; ?>" />
</td>
<td style="color:#000;font-family:Times New Roman; width:1500px; font-size:14px;" align="left">
<table border="1">
 <tr> 
<?php if($month==1){ for($i=1; $i<=31; $i++) { $SqlEmp2=mysql_query("SELECT * FROM hrm_employee_attendance WHERE EmployeeID =".$ResEmp['EmployeeID']." AND AttDate='".date($Y."-".$month."-".$i)."'", $con); $ResEmp2=mysql_fetch_array($SqlEmp2); ?>
<td align="center" class="cell2" <?php if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))==0) {echo 'bgcolor="#6B983A"';} ?> width="45" <?php if($ResEmp2['AttValue']=='HO'){echo 'bgcolor="#A9D3F5"';} elseif($ResEmp2['AttValue']=='CL' OR $ResEmp2['AttValue']=='SL' OR $ResEmp2['AttValue']=='PL' OR $ResEmp2['AttValue']=='EL' OR $ResEmp2['AttValue']=='CH' OR $ResEmp2['AttValue']=='SH' OR $ResEmp2['AttValue']=='PH' OR $ResEmp2['AttValue']=='FL' OR $ResEmp2['AttValue']=='TL'){echo 'bgcolor="#F8FBBB"';} elseif($ResEmp2['AttValue']=='A'){echo 'bgcolor="#FAD6CF"';} elseif($ResEmp2['AttValue']=='P'){echo 'bgcolor="#FFFFFF"';} elseif($ResEmp2['AttValue']=='OD'){echo 'bgcolor="#FFA4D1"';} ?> ><?php if($ResEmp2['AttValue']==''){echo '&nbsp;';} else {echo $ResEmp2['AttValue'];} ?></td><?php } } ?>

<?php if($month==2){ if($Y==2012 OR $Y==2016 OR $Y==2020 OR $Y==2024 OR $Y==2028 OR $Y==2032 OR $Y==2036 OR $Y==2040) { $day=29; } else { $day=28;} for($i=1; $i<=$day; $i++) { $SqlEmp2=mysql_query("SELECT * FROM hrm_employee_attendance WHERE EmployeeID =".$ResEmp['EmployeeID']." AND AttDate='".date($Y."-".$month."-".$i)."'", $con); $ResEmp2=mysql_fetch_array($SqlEmp2); ?><td align="center" class="cell2" <?php if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))==0) {echo 'bgcolor="#6B983A"';} ?> width="45" <?php if($ResEmp2['AttValue']=='HO'){echo 'bgcolor="#A9D3F5"';} elseif($ResEmp2['AttValue']=='CL' OR $ResEmp2['AttValue']=='SL' OR $ResEmp2['AttValue']=='PL' OR $ResEmp2['AttValue']=='EL' OR $ResEmp2['AttValue']=='CH' OR $ResEmp2['AttValue']=='SH' OR $ResEmp2['AttValue']=='PH' OR $ResEmp2['AttValue']=='FL' OR $ResEmp2['AttValue']=='TL'){echo 'bgcolor="#F8FBBB"';} elseif($ResEmp2['AttValue']=='A'){echo 'bgcolor="#FAD6CF"';} elseif($ResEmp2['AttValue']=='P'){echo 'bgcolor="#FFFFFF"';} elseif($ResEmp2['AttValue']=='OD'){echo 'bgcolor="#FFA4D1"';} ?> ><?php if($ResEmp2['AttValue']==''){echo '&nbsp;';} else {echo $ResEmp2['AttValue'];} ?></td><?php } } ?>

<?php if($month==3){ for($i=1; $i<=31; $i++) { $SqlEmp2=mysql_query("SELECT * FROM hrm_employee_attendance WHERE EmployeeID =".$ResEmp['EmployeeID']." AND AttDate='".date($Y."-".$month."-".$i)."'", $con); $ResEmp2=mysql_fetch_array($SqlEmp2); ?><td align="center" class="cell2" <?php if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))==0) {echo 'bgcolor="#6B983A"';} ?> width="45" <?php if($ResEmp2['AttValue']=='HO'){echo 'bgcolor="#A9D3F5"';} elseif($ResEmp2['AttValue']=='CL' OR $ResEmp2['AttValue']=='SL' OR $ResEmp2['AttValue']=='PL' OR $ResEmp2['AttValue']=='EL' OR $ResEmp2['AttValue']=='CH' OR $ResEmp2['AttValue']=='SH' OR $ResEmp2['AttValue']=='PH' OR $ResEmp2['AttValue']=='FL' OR $ResEmp2['AttValue']=='TL'){echo 'bgcolor="#F8FBBB"';} elseif($ResEmp2['AttValue']=='A'){echo 'bgcolor="#FAD6CF"';} elseif($ResEmp2['AttValue']=='P'){echo 'bgcolor="#FFFFFF"';} elseif($ResEmp2['AttValue']=='OD'){echo 'bgcolor="#FFA4D1"';} ?> ><?php if($ResEmp2['AttValue']==''){echo '&nbsp;';} else {echo $ResEmp2['AttValue'];} ?></td><?php } } ?>

<?php if($month==4){ for($i=1; $i<=30; $i++) { $SqlEmp2=mysql_query("SELECT * FROM hrm_employee_attendance WHERE EmployeeID =".$ResEmp['EmployeeID']." AND AttDate='".date($Y."-".$month."-".$i)."'", $con); $ResEmp2=mysql_fetch_array($SqlEmp2); ?><td align="center" class="cell2" <?php if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))==0) {echo 'bgcolor="#6B983A"';} ?> width="45" <?php if($ResEmp2['AttValue']=='HO'){echo 'bgcolor="#A9D3F5"';} elseif($ResEmp2['AttValue']=='CL' OR $ResEmp2['AttValue']=='SL' OR $ResEmp2['AttValue']=='PL' OR $ResEmp2['AttValue']=='EL' OR $ResEmp2['AttValue']=='CH' OR $ResEmp2['AttValue']=='SH' OR $ResEmp2['AttValue']=='PH' OR $ResEmp2['AttValue']=='FL' OR $ResEmp2['AttValue']=='TL'){echo 'bgcolor="#F8FBBB"';} elseif($ResEmp2['AttValue']=='A'){echo 'bgcolor="#FAD6CF"';} elseif($ResEmp2['AttValue']=='P'){echo 'bgcolor="#FFFFFF"';} elseif($ResEmp2['AttValue']=='OD'){echo 'bgcolor="#FFA4D1"';} ?> ><?php if($ResEmp2['AttValue']==''){echo '&nbsp;';} else {echo $ResEmp2['AttValue'];} ?></td><?php } } ?>

<?php if($month==5){ for($i=1; $i<=31; $i++) { $SqlEmp2=mysql_query("SELECT * FROM hrm_employee_attendance WHERE EmployeeID =".$ResEmp['EmployeeID']." AND AttDate='".date($Y."-".$month."-".$i)."'", $con); $ResEmp2=mysql_fetch_array($SqlEmp2); ?><td align="center" class="cell2" <?php if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))==0) {echo 'bgcolor="#6B983A"';} ?> width="45" <?php if($ResEmp2['AttValue']=='HO'){echo 'bgcolor="#A9D3F5"';} elseif($ResEmp2['AttValue']=='CL' OR $ResEmp2['AttValue']=='SL' OR $ResEmp2['AttValue']=='PL' OR $ResEmp2['AttValue']=='EL' OR $ResEmp2['AttValue']=='CH' OR $ResEmp2['AttValue']=='SH' OR $ResEmp2['AttValue']=='PH' OR $ResEmp2['AttValue']=='FL' OR $ResEmp2['AttValue']=='TL'){echo 'bgcolor="#F8FBBB"';} elseif($ResEmp2['AttValue']=='A'){echo 'bgcolor="#FAD6CF"';} elseif($ResEmp2['AttValue']=='P'){echo 'bgcolor="#FFFFFF"';} elseif($ResEmp2['AttValue']=='OD'){echo 'bgcolor="#FFA4D1"';} ?> ><?php if($ResEmp2['AttValue']==''){echo '&nbsp;';} else {echo $ResEmp2['AttValue'];} ?></td><?php } } ?>

<?php if($month==6){ for($i=1; $i<=30; $i++) { $SqlEmp2=mysql_query("SELECT * FROM hrm_employee_attendance WHERE EmployeeID =".$ResEmp['EmployeeID']." AND AttDate='".date($Y."-".$month."-".$i)."'", $con); $ResEmp2=mysql_fetch_array($SqlEmp2); ?><td align="center" class="cell2" <?php if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))==0) {echo 'bgcolor="#6B983A"';} ?> width="45" <?php if($ResEmp2['AttValue']=='HO'){echo 'bgcolor="#A9D3F5"';} elseif($ResEmp2['AttValue']=='CL' OR $ResEmp2['AttValue']=='SL' OR $ResEmp2['AttValue']=='PL' OR $ResEmp2['AttValue']=='EL' OR $ResEmp2['AttValue']=='CH' OR $ResEmp2['AttValue']=='SH' OR $ResEmp2['AttValue']=='PH' OR $ResEmp2['AttValue']=='FL' OR $ResEmp2['AttValue']=='TL'){echo 'bgcolor="#F8FBBB"';} elseif($ResEmp2['AttValue']=='A'){echo 'bgcolor="#FAD6CF"';} elseif($ResEmp2['AttValue']=='P'){echo 'bgcolor="#FFFFFF"';} elseif($ResEmp2['AttValue']=='OD'){echo 'bgcolor="#FFA4D1"';} ?> ><?php if($ResEmp2['AttValue']==''){echo '&nbsp;';} else {echo $ResEmp2['AttValue'];} ?></td><?php } } ?>

<?php if($month==7){ for($i=1; $i<=31; $i++) { $SqlEmp2=mysql_query("SELECT * FROM hrm_employee_attendance WHERE EmployeeID =".$ResEmp['EmployeeID']." AND AttDate='".date($Y."-".$month."-".$i)."'", $con); $ResEmp2=mysql_fetch_array($SqlEmp2); ?><td align="center" class="cell2" <?php if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))==0) {echo 'bgcolor="#6B983A"';} ?> width="45" <?php if($ResEmp2['AttValue']=='HO'){echo 'bgcolor="#A9D3F5"';} elseif($ResEmp2['AttValue']=='CL' OR $ResEmp2['AttValue']=='SL' OR $ResEmp2['AttValue']=='PL' OR $ResEmp2['AttValue']=='EL' OR $ResEmp2['AttValue']=='CH' OR $ResEmp2['AttValue']=='SH' OR $ResEmp2['AttValue']=='PH' OR $ResEmp2['AttValue']=='FL' OR $ResEmp2['AttValue']=='TL'){echo 'bgcolor="#F8FBBB"';} elseif($ResEmp2['AttValue']=='A'){echo 'bgcolor="#FAD6CF"';} elseif($ResEmp2['AttValue']=='P'){echo 'bgcolor="#FFFFFF"';} elseif($ResEmp2['AttValue']=='OD'){echo 'bgcolor="#FFA4D1"';} ?> ><?php if($ResEmp2['AttValue']==''){echo '&nbsp;';} else {echo $ResEmp2['AttValue'];} ?></td><?php } } ?>

<?php if($month==8){ for($i=1; $i<=31; $i++) { $SqlEmp2=mysql_query("SELECT * FROM hrm_employee_attendance WHERE EmployeeID =".$ResEmp['EmployeeID']." AND AttDate='".date($Y."-".$month."-".$i)."'", $con); $ResEmp2=mysql_fetch_array($SqlEmp2); ?><td align="center" class="cell2" <?php if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))==0) {echo 'bgcolor="#6B983A"';} ?> width="45" <?php if($ResEmp2['AttValue']=='HO'){echo 'bgcolor="#A9D3F5"';} elseif($ResEmp2['AttValue']=='CL' OR $ResEmp2['AttValue']=='SL' OR $ResEmp2['AttValue']=='PL' OR $ResEmp2['AttValue']=='EL' OR $ResEmp2['AttValue']=='CH' OR $ResEmp2['AttValue']=='SH' OR $ResEmp2['AttValue']=='PH' OR $ResEmp2['AttValue']=='FL' OR $ResEmp2['AttValue']=='TL'){echo 'bgcolor="#F8FBBB"';} elseif($ResEmp2['AttValue']=='A'){echo 'bgcolor="#FAD6CF"';} elseif($ResEmp2['AttValue']=='P'){echo 'bgcolor="#FFFFFF"';} elseif($ResEmp2['AttValue']=='OD'){echo 'bgcolor="#FFA4D1"';} ?> ><?php if($ResEmp2['AttValue']==''){echo '&nbsp;';} else {echo $ResEmp2['AttValue'];} ?></td><?php } } ?>

<?php if($month==9){ for($i=1; $i<=30; $i++) { $SqlEmp2=mysql_query("SELECT * FROM hrm_employee_attendance WHERE EmployeeID =".$ResEmp['EmployeeID']." AND AttDate='".date($Y."-".$month."-".$i)."'", $con); $ResEmp2=mysql_fetch_array($SqlEmp2); ?><td align="center" class="cell2" <?php if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))==0) {echo 'bgcolor="#6B983A"';} ?> width="45" <?php if($ResEmp2['AttValue']=='HO'){echo 'bgcolor="#A9D3F5"';} elseif($ResEmp2['AttValue']=='CL' OR $ResEmp2['AttValue']=='SL' OR $ResEmp2['AttValue']=='PL' OR $ResEmp2['AttValue']=='EL' OR $ResEmp2['AttValue']=='CH' OR $ResEmp2['AttValue']=='SH' OR $ResEmp2['AttValue']=='PH' OR $ResEmp2['AttValue']=='FL' OR $ResEmp2['AttValue']=='TL'){echo 'bgcolor="#F8FBBB"';} elseif($ResEmp2['AttValue']=='A'){echo 'bgcolor="#FAD6CF"';} elseif($ResEmp2['AttValue']=='P'){echo 'bgcolor="#FFFFFF"';} elseif($ResEmp2['AttValue']=='OD'){echo 'bgcolor="#FFA4D1"';} ?> ><?php if($ResEmp2['AttValue']==''){echo '&nbsp;';} else {echo $ResEmp2['AttValue'];} ?></td><?php } } ?>

<?php if($month==10){ for($i=1; $i<=31; $i++) { $SqlEmp2=mysql_query("SELECT * FROM hrm_employee_attendance WHERE EmployeeID =".$ResEmp['EmployeeID']." AND AttDate='".date($Y."-".$month."-".$i)."'", $con); $ResEmp2=mysql_fetch_array($SqlEmp2); ?><td align="center" class="cell2" <?php if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))==0) {echo 'bgcolor="#6B983A"';} ?> width="45" <?php if($ResEmp2['AttValue']=='HO'){echo 'bgcolor="#A9D3F5"';} elseif($ResEmp2['AttValue']=='CL' OR $ResEmp2['AttValue']=='SL' OR $ResEmp2['AttValue']=='PL' OR $ResEmp2['AttValue']=='EL' OR $ResEmp2['AttValue']=='CH' OR $ResEmp2['AttValue']=='SH' OR $ResEmp2['AttValue']=='PH' OR $ResEmp2['AttValue']=='FL' OR $ResEmp2['AttValue']=='TL'){echo 'bgcolor="#F8FBBB"';} elseif($ResEmp2['AttValue']=='A'){echo 'bgcolor="#FAD6CF"';} elseif($ResEmp2['AttValue']=='P'){echo 'bgcolor="#FFFFFF"';} elseif($ResEmp2['AttValue']=='OD'){echo 'bgcolor="#FFA4D1"';} ?> ><?php if($ResEmp2['AttValue']==''){echo '&nbsp;';} else {echo $ResEmp2['AttValue'];} ?></td><?php } } ?>

<?php if($month==11){ for($i=1; $i<=30; $i++) { $SqlEmp2=mysql_query("SELECT * FROM hrm_employee_attendance WHERE EmployeeID =".$ResEmp['EmployeeID']." AND AttDate='".date($Y."-".$month."-".$i)."'", $con); $ResEmp2=mysql_fetch_array($SqlEmp2); ?><td align="center" class="cell2" <?php if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))==0) {echo 'bgcolor="#6B983A"';} ?> width="45" <?php if($ResEmp2['AttValue']=='HO'){echo 'bgcolor="#A9D3F5"';} elseif($ResEmp2['AttValue']=='CL' OR $ResEmp2['AttValue']=='SL' OR $ResEmp2['AttValue']=='PL' OR $ResEmp2['AttValue']=='EL' OR $ResEmp2['AttValue']=='CH' OR $ResEmp2['AttValue']=='SH' OR $ResEmp2['AttValue']=='PH' OR $ResEmp2['AttValue']=='FL' OR $ResEmp2['AttValue']=='TL'){echo 'bgcolor="#F8FBBB"';} elseif($ResEmp2['AttValue']=='A'){echo 'bgcolor="#FAD6CF"';} elseif($ResEmp2['AttValue']=='P'){echo 'bgcolor="#FFFFFF"';} elseif($ResEmp2['AttValue']=='OD'){echo 'bgcolor="#FFA4D1"';} ?> ><?php if($ResEmp2['AttValue']==''){echo '&nbsp;';} else {echo $ResEmp2['AttValue'];} ?></td><?php } } ?>

<?php if($month==12){ for($i=1; $i<=31; $i++) { $SqlEmp2=mysql_query("SELECT * FROM hrm_employee_attendance WHERE EmployeeID =".$ResEmp['EmployeeID']." AND AttDate='".date($Y."-".$month."-".$i)."'", $con); $ResEmp2=mysql_fetch_array($SqlEmp2); ?><td align="center" class="cell2" <?php if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))==0) {echo 'bgcolor="#6B983A"';} ?> width="45" <?php if($ResEmp2['AttValue']=='HO'){echo 'bgcolor="#A9D3F5"';} elseif($ResEmp2['AttValue']=='CL' OR $ResEmp2['AttValue']=='SL' OR $ResEmp2['AttValue']=='PL' OR $ResEmp2['AttValue']=='EL' OR $ResEmp2['AttValue']=='CH' OR $ResEmp2['AttValue']=='SH' OR $ResEmp2['AttValue']=='PH' OR $ResEmp2['AttValue']=='FL' OR $ResEmp2['AttValue']=='TL'){echo 'bgcolor="#F8FBBB"';} elseif($ResEmp2['AttValue']=='A'){echo 'bgcolor="#FAD6CF"';} elseif($ResEmp2['AttValue']=='P'){echo 'bgcolor="#FFFFFF"';} elseif($ResEmp2['AttValue']=='OD'){echo 'bgcolor="#FFA4D1"';} ?> ><?php if($ResEmp2['AttValue']==''){echo '&nbsp;';} else {echo $ResEmp2['AttValue'];} ?></td><?php } } ?>  
 </tr>
</table>
</td>
<?php $SqlEmp3=mysql_query("SELECT * FROM hrm_employee_monthlyleave_balance WHERE EmployeeID=".$ResEmp['EmployeeID']." AND Month=".$month." AND Year=".$Y, $con);
$ResEmp3=mysql_fetch_array($SqlEmp3); ?>
<td style="color:#FFF;font-family:Times New Roman; width:200px; font-size:14px;" align="left">
<table border="1"><tr>
<td class="cellOpe2" align="center" width="48" valign="top" style="background-color:#FFFFDD;"><?php if($month==1){echo $ResEmp3['TotCL'];} else { echo $ResEmp3['OpeningCL']; } ?></td>
<td class="cellOpe2" align="center" width="48" valign="top" style="background-color:#FFFFDD;"><?php if($month==1){echo $ResEmp3['TotSL'];} else { echo $ResEmp3['OpeningSL']; } ?></td>
<td class="cellOpe2" align="center" width="48" valign="top" style="background-color:#FFFFDD;"><?php if($month==1){echo $ResEmp3['TotPL'];} else { echo $ResEmp3['OpeningPL']; } ?></td>
<td class="cellOpe2" align="center" width="48" valign="top" style="background-color:#FFFFDD;"><?php if($month==1){echo $ResEmp3['TotEL'];} else { echo $ResEmp3['OpeningEL']; } ?></td>
</tr></table>
</td>
<td style="color:#FFF;font-family:Times New Roman; width:250px; font-size:14px;" align="center">
<?php $sqlTotAtt=mysql_query("select * from hrm_employee_monthatt where Year=".$Y." AND EmployeeID=".$ResEmp['EmployeeID']." AND Month=".$month."", $con);
      $resTotAtt=mysql_fetch_assoc($sqlTotAtt);
 ?>    <table border="1" cellspacing="0"><tr>
	  <td class="cellOpe2" align="center" style="background-color:#F8FBBB;" width="48" valign="top"><?php echo $resTotAtt['MonthAtt_TotLeave']; ?></td>
	  <td class="cellOpe2" align="center" style="background-color:#A9D3F5;" width="48" valign="top"><?php echo $resTotAtt['MonthAtt_TotHO']; ?></td>
      <td class="cellOpe2" align="center" style="background-color:#FFA4D1;" width="48" valign="top"><?php echo $resTotAtt['MonthAtt_TotOD']; ?></td>
	  <td class="cellOpe2" align="center" style="background-color:#FFFFFF;" width="48" valign="top"><?php echo $resTotAtt['MonthAtt_TotPR']; ?></td>
	  <td class="cellOpe2" align="center" style="background-color:#FAD6CF;" width="48" valign="top"><?php echo $resTotAtt['MonthAtt_TotAP']; ?></td>
	  </tr></table>
</td>
<td style="color:#000;font-family:Times New Roman; width:70px; font-size:14px;height:20px; background-color:#B6F1BD; font-weight:bold;" align="center">
<?php echo $resTotAtt['MonthAtt_TotPaidDay']; ?>
</td>
</tr>
<?php $Sno++; } ?> 	
</table>

<?php  ////////////////////////////////////////////////////////////_TABLE_2_//////////////////////////////////////////////////////////////////////// ?> 
<table  border="1" bgcolor="#FFFFFF" cellpadding="0" cellspacing="0" width="2400" id="table_2" style="display:none;">
<?php $SqlEmp=mysql_query("select hrm_employee.*,hrm_employee_general.* from hrm_employee INNER JOIN hrm_employee_general ON hrm_employee.EmployeeID=hrm_employee_general.EmployeeID where hrm_employee.EmpStatus='A' AND hrm_employee_general.DepartmentId=".$id." order by EmpCode ASC", $con); $Sno=1; 
$SqlRows=mysql_num_rows($SqlEmp); echo '<input type="hidden" name="EmpRows" id="EmpRows" value='.$SqlRows.' />'; while($ResEmp=mysql_fetch_array($SqlEmp)) { ?>
<tr>
<td style="color:#000;font-family:Times New Roman; width:40px; font-size:14px; height:20px;" align="left">&nbsp;<?php echo $Sno; ?></td>
<td style="color:#000;font-family:Times New Roman; width:80px; font-size:14px;height:20px;" align="left">&nbsp;<?php echo $ResEmp['EmpCode']; ?></td>
<td style="color:#000;font-family:Times New Roman; width:180px; font-size:14px;height:20px;" align="left">&nbsp;<?php echo $ResEmp['Fname'].' '.$ResEmp['Sname'].' '.$ResEmp['Lname']; ?>
<input type="hidden" name="EmpId<?php echo $Sno; ?>" value="<?php echo $ResEmp['EmployeeID']; ?>" />
</td>
<td align="left" style="width:1500px;">
<table border="1">
 <tr>
<?php if($month==1){ for($i=1; $i<=31; $i++) { $SqlEmp2=mysql_query("SELECT * FROM hrm_employee_attendance WHERE EmployeeID =".$ResEmp['EmployeeID']." AND AttDate='".date($Y."-".$month."-".$i)."'", $con); $ResEmp2=mysql_fetch_array($SqlEmp2); ?>
<td align="center" valign="top" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;" <?php if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))==0) {echo 'bgcolor="#6B983A"';} ?> width="45"><?php //if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))!=0) { ?>
<select name="Jan<?php echo $Sno.'_'.$i; ?>" style="width:40px; font-size:12px; height:18px; border-style:hidden;" onChange="return SelectAtt(this.value,<?php echo $ResEmp['EmployeeID']; ?>,'VJan<?php echo $Sno.'_'.$i; ?>')"><option value="<?php echo $ResEmp2['AttValue']; ?>"><?php if($ResEmp2['AttValue']==''){echo '';} else {echo $ResEmp2['AttValue'];} ?></option><option value="P">P</option><option style="background-color:#FAD6CF;" value="A">A</option><option value="HF">HF</option><option style="background-color:#F8FBBB;" value="CL">CL</option><option style="background-color:#F8FBBB;" value="SL">SL</option><option style="background-color:#F8FBBB;" value="PL">PL</option><option style="background-color:#F8FBBB;" value="EL">EL</option><option style="background-color:#F8FBBB;" value="CH">CH</option><option style="background-color:#F8FBBB;" value="SH">SH</option><option style="background-color:#F8FBBB;" value="PH">PH</option><option style="background-color:#F8FBBB;" value="FL">FL</option><option style="background-color:#F8FBBB;" value="TL">TL</option><option style="background-color:#FFA4D1;" value="OD">OD</option><option style="background-color:#A9D3F5;" value="HO">HO</option><option style="background-color:#FFFFFF;" value=""></option>
</select><input type="hidden" style="width:40px;"  id="<?php echo 'VJan'.$Sno.'_'.$i; ?>" value="" /><?php //} else { echo ' '; }  ?></td><?php } } ?>

<?php if($month==2){ if(date("Y")==2012 OR date("Y")==2016 OR date("Y")==2020 OR date("Y")==2024 OR date("Y")==2028 OR date("Y")==2032 OR date("Y")==2036 OR date("Y")==2040) { $day=29; } else { $day=28;} for($i=1; $i<=$day; $i++) { $SqlEmp2=mysql_query("SELECT * FROM hrm_employee_attendance WHERE EmployeeID =".$ResEmp['EmployeeID']." AND AttDate='".date($Y."-".$month."-".$i)."'", $con); $ResEmp2=mysql_fetch_array($SqlEmp2); ?>
<td align="center" valign="top" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;" <?php if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))==0) {echo 'bgcolor="#6B983A"';} ?> width="45"><?php //if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))!=0) { ?>
<select name="Feb<?php echo $Sno.'_'.$i; ?>" style="width:40px; font-size:12px; height:18px;border-style:hidden;" onChange="return SelectAtt(this.value,<?php echo $ResEmp['EmployeeID']; ?>,'VFeb<?php echo $Sno.'_'.$i; ?>')"><option value="<?php echo $ResEmp2['AttValue'];?>"><?php if($ResEmp2['AttValue']==''){echo '';} else {echo $ResEmp2['AttValue'];} ?></option><option value="P">P</option><option style="background-color:#FAD6CF;" value="A">A</option><option value="HF">HF</option><option style="background-color:#F8FBBB;" value="CL">CL</option><option style="background-color:#F8FBBB;" value="SL">SL</option><option style="background-color:#F8FBBB;" value="PL">PL</option><option style="background-color:#F8FBBB;" value="EL">EL</option><option style="background-color:#F8FBBB;" value="CH">CH</option><option style="background-color:#F8FBBB;" value="SH">SH</option><option style="background-color:#F8FBBB;" value="PH">PH</option><option style="background-color:#F8FBBB;" value="FL">FL</option><option style="background-color:#F8FBBB;" value="TL">TL</option><option style="background-color:#FFA4D1;" value="OD">OD</option><option style="background-color:#A9D3F5;" value="HO">HO</option><option style="background-color:#FFFFFF;" value=""></option>
</select><input type="hidden" style="width:40px;"  id="<?php echo 'VFeb'.$Sno.'_'.$i; ?>" value="" /><?php //} else { echo ' '; }  ?></td><?php } } ?>

<?php if($month==3){ for($i=1; $i<=31; $i++) { $SqlEmp2=mysql_query("SELECT * FROM hrm_employee_attendance WHERE EmployeeID =".$ResEmp['EmployeeID']." AND AttDate='".date($Y."-".$month."-".$i)."'", $con); $ResEmp2=mysql_fetch_array($SqlEmp2); ?>
<td align="center" valign="top" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;" <?php if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))==0) {echo 'bgcolor="#6B983A"';} ?> width="45"><?php //if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))!=0) { ?>
<select name="March<?php echo $Sno.'_'.$i; ?>" style="width:40px; font-size:12px; height:18px;border-style:hidden;" onChange="return SelectAtt(this.value,<?php echo $ResEmp['EmployeeID']; ?>,'VMarch<?php echo $Sno.'_'.$i; ?>')"><option value="<?php echo $ResEmp2['AttValue']; ?>"><?php if($ResEmp2['AttValue']==''){echo '';} else {echo $ResEmp2['AttValue'];} ?></option><option value="P">P</option><option style="background-color:#FAD6CF;" value="A">A</option><option value="HF">HF</option><option style="background-color:#F8FBBB;" value="CL">CL</option><option style="background-color:#F8FBBB;" value="SL">SL</option><option style="background-color:#F8FBBB;" value="PL">PL</option><option style="background-color:#F8FBBB;" value="EL">EL</option><option style="background-color:#F8FBBB;" value="CH">CH</option><option style="background-color:#F8FBBB;" value="SH">SH</option><option style="background-color:#F8FBBB;" value="PH">PH</option><option style="background-color:#F8FBBB;" value="FL">FL</option><option style="background-color:#F8FBBB;" value="TL">TL</option><option style="background-color:#FFA4D1;" value="OD">OD</option><option style="background-color:#A9D3F5;" value="HO">HO</option><option style="background-color:#FFFFFF;" value=""></option>
</select><input type="hidden" style="width:40px;"  id="<?php echo 'VMarch'.$Sno.'_'.$i; ?>" value="" /><?php //} else { echo ' '; }  ?></td><?php } } ?>

<?php if($month==4){ for($i=1; $i<=30; $i++) {$SqlEmp2=mysql_query("SELECT * FROM hrm_employee_attendance WHERE EmployeeID =".$ResEmp['EmployeeID']." AND AttDate='".date($Y."-".$month."-".$i)."'", $con); $ResEmp2=mysql_fetch_array($SqlEmp2); ?>
<td align="center" valign="top" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;" <?php if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))==0) {echo 'bgcolor="#6B983A"';} ?> width="45"><?php //if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))!=0) { ?>
<select name="Apr<?php echo $Sno.'_'.$i; ?>" style="width:40px; font-size:12px; height:18px;border-style:hidden;" onChange="return SelectAtt(this.value,<?php echo $ResEmp['EmployeeID']; ?>,'VApr<?php echo $Sno.'_'.$i; ?>')"><option value="<?php echo $ResEmp2['AttValue']; ?>"><?php if($ResEmp2['AttValue']==''){echo '';} else {echo $ResEmp2['AttValue'];} ?></option><option value="P">P</option><option style="background-color:#FAD6CF;" value="A">A</option><option value="HF">HF</option><option style="background-color:#F8FBBB;" value="CL">CL</option><option style="background-color:#F8FBBB;" value="SL">SL</option><option style="background-color:#F8FBBB;" value="PL">PL</option><option style="background-color:#F8FBBB;" value="EL">EL</option><option style="background-color:#F8FBBB;" value="CH">CH</option><option style="background-color:#F8FBBB;" value="SH">SH</option><option style="background-color:#F8FBBB;" value="PH">PH</option><option style="background-color:#F8FBBB;" value="FL">FL</option><option style="background-color:#F8FBBB;" value="TL">TL</option><option style="background-color:#FFA4D1;" value="OD">OD</option><option style="background-color:#A9D3F5;" value="HO">HO</option><option style="background-color:#FFFFFF;" value=""></option>
</select><input type="hidden" style="width:40px;"  id="<?php echo 'VApr'.$Sno.'_'.$i; ?>" value="" /><?php //} else { echo ' '; }  ?></td><?php } } ?>

<?php if($month==5){ for($i=1; $i<=31; $i++) { $SqlEmp2=mysql_query("SELECT * FROM hrm_employee_attendance WHERE EmployeeID =".$ResEmp['EmployeeID']." AND AttDate='".date($Y."-".$month."-".$i)."'", $con); $ResEmp2=mysql_fetch_array($SqlEmp2); ?>
<td align="center" valign="top" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;" <?php if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))==0) {echo 'bgcolor="#6B983A"';} ?> width="45"><?php //if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))!=0) { ?>
<select name="May<?php echo $Sno.'_'.$i; ?>" style="width:40px; font-size:12px; height:18px;border-style:hidden;" onChange="return SelectAtt(this.value,<?php echo $ResEmp['EmployeeID']; ?>,'VMay<?php echo $Sno.'_'.$i; ?>')"><option value="<?php echo $ResEmp2['AttValue']; ?>"><?php if($ResEmp2['AttValue']==''){echo '';} else {echo $ResEmp2['AttValue'];} ?></option><option value="P">P</option><option style="background-color:#FAD6CF;" value="A">A</option><option value="HF">HF</option><option style="background-color:#F8FBBB;" value="CL">CL</option><option style="background-color:#F8FBBB;" value="SL">SL</option><option style="background-color:#F8FBBB;" value="PL">PL</option><option style="background-color:#F8FBBB;" value="EL">EL</option><option style="background-color:#F8FBBB;" value="CH">CH</option><option style="background-color:#F8FBBB;" value="SH">SH</option><option style="background-color:#F8FBBB;" value="PH">PH</option><option style="background-color:#F8FBBB;" value="FL">FL</option><option style="background-color:#F8FBBB;" value="TL">TL</option><option style="background-color:#FFA4D1;" value="OD">OD</option><option style="background-color:#A9D3F5;" value="HO">HO</option><option style="background-color:#FFFFFF;" value=""></option>
</select><input type="hidden" style="width:40px;"  id="<?php echo 'VMay'.$Sno.'_'.$i; ?>" value="" /><?php //} else { echo ' '; }  ?></td><?php } } ?>

<?php if($month==6){ for($i=1; $i<=30; $i++) { $SqlEmp2=mysql_query("SELECT * FROM hrm_employee_attendance WHERE EmployeeID =".$ResEmp['EmployeeID']." AND AttDate='".date($Y."-".$month."-".$i)."'", $con); $ResEmp2=mysql_fetch_array($SqlEmp2); ?>
<td align="center" valign="top" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;" <?php if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))==0) {echo 'bgcolor="#6B983A"';} ?> width="45"><?php //if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))!=0) { ?>
<select name="June<?php echo $Sno.'_'.$i; ?>" style="width:40px; font-size:12px; height:18px;border-style:hidden;" onChange="return SelectAtt(this.value,<?php echo $ResEmp['EmployeeID']; ?>,'VJune<?php echo $Sno.'_'.$i; ?>')"><option value="<?php echo $ResEmp2['AttValue']; ?>"><?php if($ResEmp2['AttValue']==''){echo '';} else {echo $ResEmp2['AttValue'];} ?></option><option value="P">P</option><option style="background-color:#FAD6CF;" value="A">A</option><option value="HF">HF</option><option style="background-color:#F8FBBB;" value="CL">CL</option><option style="background-color:#F8FBBB;" value="SL">SL</option><option style="background-color:#F8FBBB;" value="PL">PL</option><option style="background-color:#F8FBBB;" value="EL">EL</option><option style="background-color:#F8FBBB;" value="CH">CH</option><option style="background-color:#F8FBBB;" value="SH">SH</option><option style="background-color:#F8FBBB;" value="PH">PH</option><option style="background-color:#F8FBBB;" value="FL">FL</option><option style="background-color:#F8FBBB;" value="TL">TL</option><option style="background-color:#FFA4D1;" value="OD">OD</option><option style="background-color:#A9D3F5;" value="HO">HO</option><option style="background-color:#FFFFFF;" value=""></option>
</select><input type="hidden" style="width:40px;"  id="<?php echo 'VJune'.$Sno.'_'.$i; ?>" value="" /><?php //} else { echo ' '; }  ?></td><?php } } ?>

<?php if($month==7){ for($i=1; $i<=31; $i++) { $SqlEmp2=mysql_query("SELECT * FROM hrm_employee_attendance WHERE EmployeeID =".$ResEmp['EmployeeID']." AND AttDate='".date($Y."-".$month."-".$i)."'", $con); $ResEmp2=mysql_fetch_array($SqlEmp2); ?>
<td align="center" valign="top" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;" <?php if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))==0) {echo 'bgcolor="#6B983A"';} ?> width="45"><?php //if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))!=0) { ?>
<select name="July<?php echo $Sno.'_'.$i; ?>" style="width:40px; font-size:12px; height:18px;border-style:hidden;" onChange="return SelectAtt(this.value,<?php echo $ResEmp['EmployeeID']; ?>,'VJuly<?php echo $Sno.'_'.$i; ?>')"><option value="<?php echo $ResEmp2['AttValue']; ?>"><?php if($ResEmp2['AttValue']==''){echo '';} else {echo $ResEmp2['AttValue'];} ?></option><option value="P">P</option><option style="background-color:#FAD6CF;" value="A">A</option><option value="HF">HF</option><option style="background-color:#F8FBBB;" value="CL">CL</option><option style="background-color:#F8FBBB;" value="SL">SL</option><option style="background-color:#F8FBBB;" value="PL">PL</option><option style="background-color:#F8FBBB;" value="EL">EL</option><option style="background-color:#F8FBBB;" value="CH">CH</option><option style="background-color:#F8FBBB;" value="SH">SH</option><option style="background-color:#F8FBBB;" value="PH">PH</option><option style="background-color:#F8FBBB;" value="FL">FL</option><option style="background-color:#F8FBBB;" value="TL">TL</option><option style="background-color:#FFA4D1;" value="OD">OD</option><option style="background-color:#A9D3F5;" value="HO">HO</option><option style="background-color:#FFFFFF;" value=""></option>
</select><input type="hidden" style="width:40px;"  id="<?php echo 'VJuly'.$Sno.'_'.$i; ?>" value="" /><?php //} else { echo ' '; }  ?></td><?php } } ?>

<?php if($month==8){ for($i=1; $i<=31; $i++) { $SqlEmp2=mysql_query("SELECT * FROM hrm_employee_attendance WHERE EmployeeID =".$ResEmp['EmployeeID']." AND AttDate='".date($Y."-".$month."-".$i)."'", $con); $ResEmp2=mysql_fetch_array($SqlEmp2); ?>
<td align="center" valign="top" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;" <?php if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))==0) {echo 'bgcolor="#6B983A"';} ?> width="45"><?php //if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))!=0) { ?>
<select name="Aug<?php echo $Sno.'_'.$i; ?>" style="width:40px; font-size:12px; height:18px;border-style:hidden;" onChange="return SelectAtt(this.value,<?php echo $ResEmp['EmployeeID']; ?>,'VAug<?php echo $Sno.'_'.$i; ?>')"><option value="<?php echo $ResEmp2['AttValue']; ?>"><?php if($ResEmp2['AttValue']==''){echo '';} else {echo $ResEmp2['AttValue'];} ?></option><option value="P">P</option><option style="background-color:#FAD6CF;" value="A">A</option><option value="HF">HF</option><option style="background-color:#F8FBBB;" value="CL">CL</option><option style="background-color:#F8FBBB;" value="SL">SL</option><option style="background-color:#F8FBBB;" value="PL">PL</option><option style="background-color:#F8FBBB;" value="EL">EL</option><option style="background-color:#F8FBBB;" value="CH">CH</option><option style="background-color:#F8FBBB;" value="SH">SH</option><option style="background-color:#F8FBBB;" value="PH">PH</option><option style="background-color:#F8FBBB;" value="FL">FL</option><option style="background-color:#F8FBBB;" value="TL">TL</option><option style="background-color:#FFA4D1;" value="OD">OD</option><option style="background-color:#A9D3F5;" value="HO">HO</option><option style="background-color:#FFFFFF;" value=""></option>
</select><input type="hidden" style="width:40px;"  id="<?php echo 'VAug'.$Sno.'_'.$i; ?>" value="" /><?php //} else { echo ' '; }  ?></td><?php } } ?>

<?php if($month==9){ for($i=1; $i<=30; $i++) { $SqlEmp2=mysql_query("SELECT * FROM hrm_employee_attendance WHERE EmployeeID =".$ResEmp['EmployeeID']." AND AttDate='".date($Y."-".$month."-".$i)."'", $con); $ResEmp2=mysql_fetch_array($SqlEmp2); ?>
<td align="center" valign="top" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;" <?php if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))==0) {echo 'bgcolor="#6B983A"';} ?> width="45"><?php //if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))!=0) { ?>
<select name="Sep<?php echo $Sno.'_'.$i; ?>" style="width:40px; font-size:12px; height:18px;border-style:hidden;" onChange="return SelectAtt(this.value,<?php echo $ResEmp['EmployeeID']; ?>,'VSep<?php echo $Sno.'_'.$i; ?>')"><option value="<?php echo $ResEmp2['AttValue'];?>"><?php if($ResEmp2['AttValue']==''){echo '';} else {echo $ResEmp2['AttValue'];} ?></option><option value="P">P</option><option style="background-color:#FAD6CF;" value="A">A</option><option value="HF">HF</option><option style="background-color:#F8FBBB;" value="CL">CL</option><option style="background-color:#F8FBBB;" value="SL">SL</option><option style="background-color:#F8FBBB;" value="PL">PL</option><option style="background-color:#F8FBBB;" value="EL">EL</option><option style="background-color:#F8FBBB;" value="CH">CH</option><option style="background-color:#F8FBBB;" value="SH">SH</option><option style="background-color:#F8FBBB;" value="PH">PH</option><option style="background-color:#F8FBBB;" value="FL">FL</option><option style="background-color:#F8FBBB;" value="TL">TL</option><option style="background-color:#FFA4D1;" value="OD">OD</option><option style="background-color:#A9D3F5;" value="HO">HO</option><option style="background-color:#FFFFFF;" value=""></option>
</select><input type="hidden" style="width:40px;"  id="<?php echo 'VSep'.$Sno.'_'.$i; ?>" value="" /><?php //} else { echo ' '; }  ?></td><?php } } ?>

<?php if($month==10){ for($i=1; $i<=31; $i++) { $SqlEmp2=mysql_query("SELECT * FROM hrm_employee_attendance WHERE EmployeeID =".$ResEmp['EmployeeID']." AND AttDate='".date($Y."-".$month."-".$i)."'", $con); $ResEmp2=mysql_fetch_array($SqlEmp2); ?>
<td align="center" valign="top" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;" <?php if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))==0) {echo 'bgcolor="#6B983A"';} ?> width="45"><?php //if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))!=0) { ?>
<select name="Oct<?php echo $Sno.'_'.$i; ?>" style="width:40px; font-size:12px; height:18px;border-style:hidden;" onChange="return SelectAtt(this.value,<?php echo $ResEmp['EmployeeID']; ?>,'VOct<?php echo $Sno.'_'.$i; ?>')"><option value="<?php echo $ResEmp2['AttValue']; ?>"><?php if($ResEmp2['AttValue']==''){echo '';} else {echo $ResEmp2['AttValue'];} ?></option><option value="P">P</option><option style="background-color:#FAD6CF;" value="A">A</option><option value="HF">HF</option><option style="background-color:#F8FBBB;" value="CL">CL</option><option style="background-color:#F8FBBB;" value="SL">SL</option><option style="background-color:#F8FBBB;" value="PL">PL</option><option style="background-color:#F8FBBB;" value="EL">EL</option><option style="background-color:#F8FBBB;" value="CH">CH</option><option style="background-color:#F8FBBB;" value="SH">SH</option><option style="background-color:#F8FBBB;" value="PH">PH</option><option style="background-color:#F8FBBB;" value="FL">FL</option><option style="background-color:#F8FBBB;" value="TL">TL</option><option style="background-color:#FFA4D1;" value="OD">OD</option><option style="background-color:#A9D3F5;" value="HO">HO</option><option style="background-color:#FFFFFF;" value=""></option>
</select><input type="hidden" style="width:40px;"  id="<?php echo 'VOct'.$Sno.'_'.$i; ?>" value="" /><?php //} else { echo ' '; }  ?></td><?php } } ?>

<?php if($month==11){ for($i=1; $i<=30; $i++) { $SqlEmp2=mysql_query("SELECT * FROM hrm_employee_attendance WHERE EmployeeID =".$ResEmp['EmployeeID']." AND AttDate='".date($Y."-".$month."-".$i)."'", $con); $ResEmp2=mysql_fetch_array($SqlEmp2); ?>
<td align="center" valign="top" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;" <?php if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))==0) {echo 'bgcolor="#6B983A"';} ?> width="45"><?php //if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))!=0) { ?>
<select name="Nov<?php echo $Sno.'_'.$i; ?>" style="width:40px; font-size:12px; height:18px;border-style:hidden;" onChange="return SelectAtt(this.value,<?php echo $ResEmp['EmployeeID']; ?>,'VNov<?php echo $Sno.'_'.$i; ?>')"><option value="<?php echo $ResEmp2['AttValue']; ?>"><?php if($ResEmp2['AttValue']==''){echo '';} else {echo $ResEmp2['AttValue'];} ?></option><option value="P">P</option><option style="background-color:#FAD6CF;" value="A">A</option><option value="HF">HF</option><option style="background-color:#F8FBBB;" value="CL">CL</option><option style="background-color:#F8FBBB;" value="SL">SL</option><option style="background-color:#F8FBBB;" value="PL">PL</option><option style="background-color:#F8FBBB;" value="EL">EL</option><option style="background-color:#F8FBBB;" value="CH">CH</option><option style="background-color:#F8FBBB;" value="SH">SH</option><option style="background-color:#F8FBBB;" value="PH">PH</option><option style="background-color:#F8FBBB;" value="FL">FL</option><option style="background-color:#F8FBBB;" value="TL">TL</option><option style="background-color:#FFA4D1;" value="OD">OD</option><option style="background-color:#A9D3F5;" value="HO">HO</option><option style="background-color:#FFFFFF;" value=""></option>
</select><input type="hidden" style="width:40px;"  id="<?php echo 'VNov'.$Sno.'_'.$i; ?>" value="" /><?php //} else { echo ' '; }  ?></td><?php } } ?>

<?php if($month==12){ for($i=1; $i<=31; $i++) { $SqlEmp2=mysql_query("SELECT * FROM hrm_employee_attendance WHERE EmployeeID =".$ResEmp['EmployeeID']." AND AttDate='".date($Y."-".$month."-".$i)."'", $con); $ResEmp2=mysql_fetch_array($SqlEmp2); ?>
<td align="center" valign="top" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;" <?php if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))==0) {echo 'bgcolor="#6B983A"';} ?> width="45"><?php //if(date("w",strtotime(date($Y.'-'.$month.'-'.$i)))!=0) { ?>
<select name="Dec<?php echo $Sno.'_'.$i; ?>" style="width:40px; font-size:12px; height:18px;border-style:hidden;" onChange="return SelectAtt(this.value,<?php echo $ResEmp['EmployeeID']; ?>,'VDec<?php echo $Sno.'_'.$i; ?>')"><option value="<?php echo $ResEmp2['AttValue']; ?>"><?php if($ResEmp2['AttValue']==''){echo '';} else {echo $ResEmp2['AttValue'];} ?></option><option value="P">P</option><option style="background-color:#FAD6CF;" value="A">A</option><option value="HF">HF</option><option style="background-color:#F8FBBB;" value="CL">CL</option><option style="background-color:#F8FBBB;" value="SL">SL</option><option style="background-color:#F8FBBB;" value="PL">PL</option><option style="background-color:#F8FBBB;" value="EL">EL</option><option style="background-color:#F8FBBB;" value="CH">CH</option><option style="background-color:#F8FBBB;" value="SH">SH</option><option style="background-color:#F8FBBB;" value="PH">PH</option><option style="background-color:#F8FBBB;" value="FL">FL</option><option style="background-color:#F8FBBB;" value="TL">TL</option><option style="background-color:#FFA4D1;" value="OD">OD</option><option style="background-color:#A9D3F5;" value="HO">HO</option><option style="background-color:#FFFFFF;" value=""></option>
</select><input type="hidden" style="width:40px;"  id="<?php echo 'VDec'.$Sno.'_'.$i; ?>" value=""/><?php //} else { echo ' '; }  ?></td><?php } } ?>  
 </tr>
</table>
</td>
<?php $SqlEmp3=mysql_query("select * from hrm_employee_monthlyleave_balance where EmployeeID=".$ResEmp['EmployeeID']." AND Month='".$month."' AND Year=".$Y, $con);  
      $ResEmp3=mysql_fetch_array($SqlEmp3); ?>
<td style="color:#FFF;font-family:Times New Roman; width:200px; font-size:14px;" align="left">

       <table border="1"><tr>
	   <td class="cellOpe2" align="center" width="48" valign="top" style="background-color:#FFFFDD;"><input style="width:40px;text-align:center;background-color:#FFFFDD; height:19px; border-style:hidden;" id="Bal_CL<?php echo $ResEmp['EmployeeID']; ?>" value="<?php if($month==1){echo $ResEmp3['TotCL'];} else { echo $ResEmp3['OpeningCL']; } ?>"></td>
	   <td class="cellOpe2" align="center" width="48" valign="top" style="background-color:#FFFFDD;"><input style="width:40px;text-align:center;background-color:#FFFFDD;height:19px;border-style:hidden;" id="Bal_SL<?php echo $ResEmp['EmployeeID']; ?>" value="<?php if($month==1){echo $ResEmp3['TotSL'];} else { echo $ResEmp3['OpeningSL']; } ?>"></td>
       <td class="cellOpe2" align="center" width="48" valign="top" style="background-color:#FFFFDD;"><input style="width:40px;text-align:center;background-color:#FFFFDD;height:19px;border-style:hidden;" id="Bal_PL<?php echo $ResEmp['EmployeeID']; ?>" value="<?php if($month==1){echo $ResEmp3['TotPL'];} else { echo $ResEmp3['OpeningPL']; } ?>"></td>
	   <td class="cellOpe2" align="center" width="48" valign="top" style="background-color:#FFFFDD;"><input style="width:40px;text-align:center;background-color:#FFFFDD;height:19px;border-style:hidden;" id="Bal_EL<?php echo $ResEmp['EmployeeID']; ?>" value="<?php if($month==1){echo $ResEmp3['TotEL'];} else { echo $ResEmp3['OpeningEL']; } ?>"></td>
	   </tr></table>
</td><td style="color:#FFF;font-family:Times New Roman; width:250px; font-size:14px;" align="center">
<?php if($month==1 OR $month==3 OR $month==5 OR $month==7 OR $month==8 OR $month==10 OR $month==12){ 
      $SqlCL=mysql_query("select count(AttValue)as CL from hrm_employee_attendance where AttValue='CL' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-31")."')", $con);
	   $SqlCH=mysql_query("select count(AttValue)as CH from hrm_employee_attendance where AttValue='CH' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-31")."')", $con);
	   $SqlSL=mysql_query("select count(AttValue)as SL from hrm_employee_attendance where AttValue='SL' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-31")."')", $con);
	   $SqlSH=mysql_query("select count(AttValue)as SH from hrm_employee_attendance where AttValue='SH' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-31")."')", $con);
	   $SqlPH=mysql_query("select count(AttValue)as PH from hrm_employee_attendance where AttValue='PH' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-31")."')", $con);
	   $SqlPL=mysql_query("select count(AttValue)as PL from hrm_employee_attendance where AttValue='PL' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-31")."')", $con);
	   $SqlEL=mysql_query("select count(AttValue)as EL from hrm_employee_attendance where AttValue='EL' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-31")."')", $con);
	   $SqlFL=mysql_query("select count(AttValue)as FL from hrm_employee_attendance where AttValue='FL' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-31")."')", $con);
	   $SqlTL=mysql_query("select count(AttValue)as TL from hrm_employee_attendance where AttValue='TL' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-31")."')", $con);
	  $SqlHf=mysql_query("select count(AttValue)as Hf from hrm_employee_attendance where AttValue='HF' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-31")."')", $con);
	  $SqlPresent=mysql_query("select count(AttValue)as Present from hrm_employee_attendance where AttValue='P' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-31")."')", $con);
	  $SqlAbsent=mysql_query("select count(AttValue)as Absent from hrm_employee_attendance where AttValue='A' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-31")."')", $con);
	  $SqlOnDuties=mysql_query("select count(AttValue)as OnDuties from hrm_employee_attendance where AttValue='OD' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-31")."')", $con);
	  $SqlHoliday=mysql_query("select count(AttValue)as Holiday from hrm_employee_attendance where AttValue='HO' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-31")."')", $con); 
	  $SqlELSun=mysql_query("select count(CheckSunday)as SUN from hrm_employee_attendance where CheckSunday='Y' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-31")."')", $con); } 
	 
	  elseif($month==2){ if(date("Y")==2012 OR date("Y")==2016 OR date("Y")==2020 OR date("Y")==2024 OR date("Y")==2028 OR date("Y")==2032 OR date("Y")==2036 OR date("Y")==2040) { $day=29; } else { $day=28;}
     $SqlCL=mysql_query("select count(AttValue)as CL from hrm_employee_attendance where AttValue='CL' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-".$day)."')", $con);
	   $SqlCH=mysql_query("select count(AttValue)as CH from hrm_employee_attendance where AttValue='CH' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-".$day)."')", $con);
	   $SqlSL=mysql_query("select count(AttValue)as SL from hrm_employee_attendance where AttValue='SL' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-".$day)."')", $con);
	   $SqlSH=mysql_query("select count(AttValue)as SH from hrm_employee_attendance where AttValue='SH' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-".$day)."')", $con);
	    $SqlPH=mysql_query("select count(AttValue)as PH from hrm_employee_attendance where AttValue='PH' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-".$day)."')", $con);
	   $SqlPL=mysql_query("select count(AttValue)as PL from hrm_employee_attendance where AttValue='PL' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-".$day)."')", $con);
	   $SqlEL=mysql_query("select count(AttValue)as EL from hrm_employee_attendance where AttValue='EL' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-".$day)."')", $con);
	   $SqlFL=mysql_query("select count(AttValue)as FL from hrm_employee_attendance where AttValue='FL' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-".$day)."')", $con);
	   $SqlTL=mysql_query("select count(AttValue)as TL from hrm_employee_attendance where AttValue='TL' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-".$day)."')", $con);
	  $SqlHf=mysql_query("select count(AttValue)as Hf from hrm_employee_attendance where AttValue='HF' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-".$day)."')", $con);
	  $SqlPresent=mysql_query("select count(AttValue)as Present from hrm_employee_attendance where AttValue='P' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-".$day)."')", $con);
	  $SqlAbsent=mysql_query("select count(AttValue)as Absent from hrm_employee_attendance where AttValue='A' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-".$day)."')", $con);
	  $SqlOnDuties=mysql_query("select count(AttValue)as OnDuties from hrm_employee_attendance where AttValue='OD' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-".$day)."')", $con);
	  $SqlHoliday=mysql_query("select count(AttValue)as Holiday from hrm_employee_attendance where AttValue='HO' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-".$day)."')", $con); 
	  $SqlELSun=mysql_query("select count(CheckSunday)as SUN from hrm_employee_attendance where CheckSunday='Y' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-".$day)."')", $con);}  
	  
	  elseif($month==4 OR $month==6 OR $month==9 OR $month==11){ 
      $SqlCL=mysql_query("select count(AttValue)as CL from hrm_employee_attendance where AttValue='CL' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-30")."')", $con);
	   $SqlCH=mysql_query("select count(AttValue)as CH from hrm_employee_attendance where AttValue='CH' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-30")."')", $con);
	   $SqlSL=mysql_query("select count(AttValue)as SL from hrm_employee_attendance where AttValue='SL' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-30")."')", $con);
	   $SqlSH=mysql_query("select count(AttValue)as SH from hrm_employee_attendance where AttValue='SH' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-30")."')", $con);
	   $SqlPH=mysql_query("select count(AttValue)as PH from hrm_employee_attendance where AttValue='PH' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-30")."')", $con);
	   $SqlPL=mysql_query("select count(AttValue)as PL from hrm_employee_attendance where AttValue='PL' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-30")."')", $con);
	   $SqlEL=mysql_query("select count(AttValue)as EL from hrm_employee_attendance where AttValue='EL' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-30")."')", $con);
	   $SqlFL=mysql_query("select count(AttValue)as FL from hrm_employee_attendance where AttValue='FL' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-30")."')", $con);
	   $SqlTL=mysql_query("select count(AttValue)as TL from hrm_employee_attendance where AttValue='TL' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-30")."')", $con);
	  $SqlHf=mysql_query("select count(AttValue)as Hf from hrm_employee_attendance where AttValue='HF' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-30")."')", $con);
	  $SqlPresent=mysql_query("select count(AttValue)as Present from hrm_employee_attendance where AttValue='P' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-30")."')", $con);
	  $SqlAbsent=mysql_query("select count(AttValue)as Absent from hrm_employee_attendance where AttValue='A' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-30")."')", $con);
	  $SqlOnDuties=mysql_query("select count(AttValue)as OnDuties from hrm_employee_attendance where AttValue='OD' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-30")."')", $con);
	  $SqlHoliday=mysql_query("select count(AttValue)as Holiday from hrm_employee_attendance where AttValue='HO' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-30")."')", $con); 
	  $SqlELSun=mysql_query("select count(CheckSunday)as SUN from hrm_employee_attendance where CheckSunday='Y' AND EmployeeID=".$ResEmp['EmployeeID']." AND (AttDate between '".date($Y."-".$month."-1")."' AND '".date($Y."-".$month."-30")."')", $con); }
	   

   $ResCL=mysql_fetch_array($SqlCL); $ResCH=mysql_fetch_array($SqlCH); $ResSL=mysql_fetch_array($SqlSL); $ResSH=mysql_fetch_array($SqlSH); $ResPH=mysql_fetch_array($SqlPH);
   $ResPL=mysql_fetch_array($SqlPL); $ResEL=mysql_fetch_array($SqlEL); $ResFL=mysql_fetch_array($SqlFL); $ResTL=mysql_fetch_array($SqlTL); $ResHf=mysql_fetch_array($SqlHf); 
   $ResPresent=mysql_fetch_array($SqlPresent); 
   $ResAbsent=mysql_fetch_array($SqlAbsent); $ResOnDuties=mysql_fetch_array($SqlOnDuties); $ResHoliday=mysql_fetch_array($SqlHoliday); 
   $ResELSun=mysql_fetch_array($SqlELSun);
  
   $CountCL=$ResCL['CL']; $CountCH=$ResCH['CH']/2; $TotalCL=$CountCL+$CountCH; $CountSL=$ResSL['SL']; $CountSH=$ResSH['SH']/2; $TotalSL=$CountSL+$CountSH;
   $CountPH=$ResPH['PH']/2; $TotalPL=$ResPL['PL']+$CountPH; $TotalEL=$ResEL['EL']; $TotalFL=$ResFL['FL']; $TotalTL=$ResTL['TL']; 
   $TotalLeaveCount=$TotalCL+$TotalSL+$TotalPL+$TotalEL+$TotalFL+$TotalTL; $TotELSun=$ResELSun['SUN'];
   $CountHf=$ResHf['Hf']/2; //$CountHf=$ResHf['Hf']/2;  
   $TotalPR=$ResPresent['Present']+$CountCH+$CountSH+$CountPH+$CountHf;  //$TotalPR=$ResPresent['Present']+$CountHf; 
   $TotalAbsent=$ResAbsent['Absent']+$CountHf;
   $TotalOnDuties=$ResOnDuties['OnDuties']; $TotalHoliday=$ResHoliday['Holiday']; 
   
   $TotalDayWithSunEL=$TotalPR+$TotalLeaveCount+$TotalOnDuties+$TotalHoliday;
   $TotalPaidDay=$TotalDayWithSunEL-$TotELSun;
   $TotalWorkingDay=26;
?>

<input type="hidden" id="Tot_Leave<?php echo $ResEmp['EmployeeID']; ?>"  value="<?php echo $TotalLeaveCount; ?>">
<input type="hidden" id="Tot_Holiday<?php echo $ResEmp['EmployeeID']; ?>"  value="<?php echo $TotalHoliday; ?>">
<input type="hidden" id="Tot_OnDuties<?php echo $ResEmp['EmployeeID']; ?>"  value="<?php echo $TotalOnDuties; ?>">
<input type="hidden" id="Tot_Absent<?php echo $ResEmp['EmployeeID']; ?>"  value="<?php echo $TotalPR; ?>">
<input type="hidden" id="Tot_Present<?php echo $ResEmp['EmployeeID']; ?>" value="<?php echo $TotalAbsent; ?>">

	  <table border="1" cellspacing="0"><tr>
	  <td class="cellOpe2" align="center" style="background-color:#F8FBBB;" width="48" valign="top"><?php echo $TotalLeaveCount; ?></td>
	  <td class="cellOpe2" align="center" style="background-color:#A9D3F5;" width="48" valign="top"><?php echo $TotalHoliday; ?></td>
      <td class="cellOpe2" align="center" style="background-color:#FFA4D1;" width="48" valign="top"><?php echo $TotalOnDuties; ?></td>
	  <td class="cellOpe2" align="center" style="background-color:#FFFFFF;" width="48" valign="top"><?php echo $TotalPR; ?></td>
	  <td class="cellOpe2" align="center" style="background-color:#FAD6CF;" width="48" valign="top"><?php echo $TotalAbsent; ?></td>
	  </tr></table>
	  
</td>
<td style="color:#000;font-family:Times New Roman; width:70px; font-size:14px;height:20px; background-color:#B6F1BD; font-weight:bold;" align="center">
<?php echo $TotalPaidDay; ?><input type="hidden" name="PaidDay<?php echo $ResEmp['EmployeeID']; ?>" id="PaidDay<?php echo $ResEmp['EmployeeID']; ?>" value="<?php echo $TotalPaidDay; ?>" />
</td>
</tr>
<?php $Sno++; } ?> 	
</table>  


<?php } ?>

